trigger:
- master

jobs:
  - job: Linux
    pool:
      vmImage: Ubuntu-18.04
    steps:
    - checkout: self
      submodules: true
    - script: |
        cmake -H. -Bbuild
        cmake --build build || true
      displayName: Build
  - job: macOS
    pool:
      vmImage: macOS-10.15
    steps:
    - checkout: self
      submodules: true
    - script: |
        cmake -H. -Bbuild
        cmake --build build || true
      displayName: Build
  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: true
    - script: |
        cmake -H. -Bbuild
        cmake --build build
      displayName: Build
